// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  TypedMap,
  Entity,
  Value,
  ValueKind,
  store,
  Address,
  Bytes,
  BigInt,
  BigDecimal
} from "@graphprotocol/graph-ts";

export class Terminal extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Terminal entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Terminal entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Terminal", id.toString(), this);
  }

  static load(id: string): Terminal | null {
    return store.get("Terminal", id) as Terminal | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get poolCount(): i32 {
    let value = this.get("poolCount");
    return value.toI32();
  }

  set poolCount(value: i32) {
    this.set("poolCount", Value.fromI32(value));
  }
}

export class Token extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Token entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Token entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Token", id.toString(), this);
  }

  static load(id: string): Token | null {
    return store.get("Token", id) as Token | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get symbol(): string {
    let value = this.get("symbol");
    return value.toString();
  }

  set symbol(value: string) {
    this.set("symbol", Value.fromString(value));
  }

  get name(): string {
    let value = this.get("name");
    return value.toString();
  }

  set name(value: string) {
    this.set("name", Value.fromString(value));
  }

  get decimals(): BigInt {
    let value = this.get("decimals");
    return value.toBigInt();
  }

  set decimals(value: BigInt) {
    this.set("decimals", Value.fromBigInt(value));
  }
}

export class Pool extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Pool entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Pool entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Pool", id.toString(), this);
  }

  static load(id: string): Pool | null {
    return store.get("Pool", id) as Pool | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get token0(): string | null {
    let value = this.get("token0");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set token0(value: string | null) {
    if (value === null) {
      this.unset("token0");
    } else {
      this.set("token0", Value.fromString(value as string));
    }
  }

  get token1(): string | null {
    let value = this.get("token1");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set token1(value: string | null) {
    if (value === null) {
      this.unset("token1");
    } else {
      this.set("token1", Value.fromString(value as string));
    }
  }

  get lowerTick(): i32 {
    let value = this.get("lowerTick");
    return value.toI32();
  }

  set lowerTick(value: i32) {
    this.set("lowerTick", Value.fromI32(value));
  }

  get upperTick(): i32 {
    let value = this.get("upperTick");
    return value.toI32();
  }

  set upperTick(value: i32) {
    this.set("upperTick", Value.fromI32(value));
  }

  get ticks(): Array<BigInt> | null {
    let value = this.get("ticks");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigIntArray();
    }
  }

  set ticks(value: Array<BigInt> | null) {
    if (value === null) {
      this.unset("ticks");
    } else {
      this.set("ticks", Value.fromBigIntArray(value as Array<BigInt>));
    }
  }

  get owner(): string | null {
    let value = this.get("owner");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set owner(value: string | null) {
    if (value === null) {
      this.unset("owner");
    } else {
      this.set("owner", Value.fromString(value as string));
    }
  }

  get manager(): string | null {
    let value = this.get("manager");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set manager(value: string | null) {
    if (value === null) {
      this.unset("manager");
    } else {
      this.set("manager", Value.fromString(value as string));
    }
  }

  get rewardTokens(): Array<string> | null {
    let value = this.get("rewardTokens");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set rewardTokens(value: Array<string> | null) {
    if (value === null) {
      this.unset("rewardTokens");
    } else {
      this.set("rewardTokens", Value.fromStringArray(value as Array<string>));
    }
  }

  get rewardAmounts(): Array<BigInt> | null {
    let value = this.get("rewardAmounts");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigIntArray();
    }
  }

  set rewardAmounts(value: Array<BigInt> | null) {
    if (value === null) {
      this.unset("rewardAmounts");
    } else {
      this.set("rewardAmounts", Value.fromBigIntArray(value as Array<BigInt>));
    }
  }

  get rewardAmountsPerWeek(): Array<BigInt> | null {
    let value = this.get("rewardAmountsPerWeek");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigIntArray();
    }
  }

  set rewardAmountsPerWeek(value: Array<BigInt> | null) {
    if (value === null) {
      this.unset("rewardAmountsPerWeek");
    } else {
      this.set(
        "rewardAmountsPerWeek",
        Value.fromBigIntArray(value as Array<BigInt>)
      );
    }
  }

  get rewardsAreEscrowed(): boolean {
    let value = this.get("rewardsAreEscrowed");
    return value.toBoolean();
  }

  set rewardsAreEscrowed(value: boolean) {
    this.set("rewardsAreEscrowed", Value.fromBoolean(value));
  }

  get rewardDuration(): BigInt | null {
    let value = this.get("rewardDuration");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set rewardDuration(value: BigInt | null) {
    if (value === null) {
      this.unset("rewardDuration");
    } else {
      this.set("rewardDuration", Value.fromBigInt(value as BigInt));
    }
  }

  get tokenId(): BigInt | null {
    let value = this.get("tokenId");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set tokenId(value: BigInt | null) {
    if (value === null) {
      this.unset("tokenId");
    } else {
      this.set("tokenId", Value.fromBigInt(value as BigInt));
    }
  }

  get poolFee(): i32 {
    let value = this.get("poolFee");
    return value.toI32();
  }

  set poolFee(value: i32) {
    this.set("poolFee", Value.fromI32(value));
  }

  get tradeFee(): BigInt | null {
    let value = this.get("tradeFee");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set tradeFee(value: BigInt | null) {
    if (value === null) {
      this.unset("tradeFee");
    } else {
      this.set("tradeFee", Value.fromBigInt(value as BigInt));
    }
  }

  get uniswapPool(): string | null {
    let value = this.get("uniswapPool");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set uniswapPool(value: string | null) {
    if (value === null) {
      this.unset("uniswapPool");
    } else {
      this.set("uniswapPool", Value.fromString(value as string));
    }
  }

  get periodFinish(): BigInt | null {
    let value = this.get("periodFinish");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set periodFinish(value: BigInt | null) {
    if (value === null) {
      this.unset("periodFinish");
    } else {
      this.set("periodFinish", Value.fromBigInt(value as BigInt));
    }
  }

  get price(): BigInt | null {
    let value = this.get("price");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set price(value: BigInt | null) {
    if (value === null) {
      this.unset("price");
    } else {
      this.set("price", Value.fromBigInt(value as BigInt));
    }
  }

  get stakedToken(): string | null {
    let value = this.get("stakedToken");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set stakedToken(value: string | null) {
    if (value === null) {
      this.unset("stakedToken");
    } else {
      this.set("stakedToken", Value.fromString(value as string));
    }
  }

  get stakedTokenBalance(): Array<BigInt> | null {
    let value = this.get("stakedTokenBalance");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigIntArray();
    }
  }

  set stakedTokenBalance(value: Array<BigInt> | null) {
    if (value === null) {
      this.unset("stakedTokenBalance");
    } else {
      this.set(
        "stakedTokenBalance",
        Value.fromBigIntArray(value as Array<BigInt>)
      );
    }
  }

  get bufferTokenBalance(): Array<BigInt> | null {
    let value = this.get("bufferTokenBalance");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigIntArray();
    }
  }

  set bufferTokenBalance(value: Array<BigInt> | null) {
    if (value === null) {
      this.unset("bufferTokenBalance");
    } else {
      this.set(
        "bufferTokenBalance",
        Value.fromBigIntArray(value as Array<BigInt>)
      );
    }
  }

  get vestingPeriod(): BigInt | null {
    let value = this.get("vestingPeriod");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set vestingPeriod(value: BigInt | null) {
    if (value === null) {
      this.unset("vestingPeriod");
    } else {
      this.set("vestingPeriod", Value.fromBigInt(value as BigInt));
    }
  }

  get createdAt(): BigInt | null {
    let value = this.get("createdAt");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigInt();
    }
  }

  set createdAt(value: BigInt | null) {
    if (value === null) {
      this.unset("createdAt");
    } else {
      this.set("createdAt", Value.fromBigInt(value as BigInt));
    }
  }

  get deposits(): Array<string> | null {
    let value = this.get("deposits");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set deposits(value: Array<string> | null) {
    if (value === null) {
      this.unset("deposits");
    } else {
      this.set("deposits", Value.fromStringArray(value as Array<string>));
    }
  }

  get withdrawals(): Array<string> | null {
    let value = this.get("withdrawals");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set withdrawals(value: Array<string> | null) {
    if (value === null) {
      this.unset("withdrawals");
    } else {
      this.set("withdrawals", Value.fromStringArray(value as Array<string>));
    }
  }

  get claimedRewards(): Array<string> | null {
    let value = this.get("claimedRewards");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set claimedRewards(value: Array<string> | null) {
    if (value === null) {
      this.unset("claimedRewards");
    } else {
      this.set("claimedRewards", Value.fromStringArray(value as Array<string>));
    }
  }

  get rewardInitiations(): Array<string> | null {
    let value = this.get("rewardInitiations");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set rewardInitiations(value: Array<string> | null) {
    if (value === null) {
      this.unset("rewardInitiations");
    } else {
      this.set(
        "rewardInitiations",
        Value.fromStringArray(value as Array<string>)
      );
    }
  }

  get vests(): Array<string> | null {
    let value = this.get("vests");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set vests(value: Array<string> | null) {
    if (value === null) {
      this.unset("vests");
    } else {
      this.set("vests", Value.fromStringArray(value as Array<string>));
    }
  }

  get collects(): Array<string> | null {
    let value = this.get("collects");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set collects(value: Array<string> | null) {
    if (value === null) {
      this.unset("collects");
    } else {
      this.set("collects", Value.fromStringArray(value as Array<string>));
    }
  }

  get reinvests(): Array<string> | null {
    let value = this.get("reinvests");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set reinvests(value: Array<string> | null) {
    if (value === null) {
      this.unset("reinvests");
    } else {
      this.set("reinvests", Value.fromStringArray(value as Array<string>));
    }
  }
}

export class Deposit extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Deposit entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Deposit entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Deposit", id.toString(), this);
  }

  static load(id: string): Deposit | null {
    return store.get("Deposit", id) as Deposit | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get user(): string {
    let value = this.get("user");
    return value.toString();
  }

  set user(value: string) {
    this.set("user", Value.fromString(value));
  }

  get pool(): string {
    let value = this.get("pool");
    return value.toString();
  }

  set pool(value: string) {
    this.set("pool", Value.fromString(value));
  }

  get amount0(): BigInt {
    let value = this.get("amount0");
    return value.toBigInt();
  }

  set amount0(value: BigInt) {
    this.set("amount0", Value.fromBigInt(value));
  }

  get amount1(): BigInt {
    let value = this.get("amount1");
    return value.toBigInt();
  }

  set amount1(value: BigInt) {
    this.set("amount1", Value.fromBigInt(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }
}

export class Withdrawal extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Withdrawal entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Withdrawal entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Withdrawal", id.toString(), this);
  }

  static load(id: string): Withdrawal | null {
    return store.get("Withdrawal", id) as Withdrawal | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get user(): string {
    let value = this.get("user");
    return value.toString();
  }

  set user(value: string) {
    this.set("user", Value.fromString(value));
  }

  get pool(): string {
    let value = this.get("pool");
    return value.toString();
  }

  set pool(value: string) {
    this.set("pool", Value.fromString(value));
  }

  get amount0(): BigInt {
    let value = this.get("amount0");
    return value.toBigInt();
  }

  set amount0(value: BigInt) {
    this.set("amount0", Value.fromBigInt(value));
  }

  get amount1(): BigInt {
    let value = this.get("amount1");
    return value.toBigInt();
  }

  set amount1(value: BigInt) {
    this.set("amount1", Value.fromBigInt(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }
}

export class RewardClaim extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save RewardClaim entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save RewardClaim entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("RewardClaim", id.toString(), this);
  }

  static load(id: string): RewardClaim | null {
    return store.get("RewardClaim", id) as RewardClaim | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get user(): string {
    let value = this.get("user");
    return value.toString();
  }

  set user(value: string) {
    this.set("user", Value.fromString(value));
  }

  get pool(): string {
    let value = this.get("pool");
    return value.toString();
  }

  set pool(value: string) {
    this.set("pool", Value.fromString(value));
  }

  get token(): string {
    let value = this.get("token");
    return value.toString();
  }

  set token(value: string) {
    this.set("token", Value.fromString(value));
  }

  get amount(): BigInt {
    let value = this.get("amount");
    return value.toBigInt();
  }

  set amount(value: BigInt) {
    this.set("amount", Value.fromBigInt(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }

  get txHash(): string {
    let value = this.get("txHash");
    return value.toString();
  }

  set txHash(value: string) {
    this.set("txHash", Value.fromString(value));
  }
}

export class RewardInitiation extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save RewardInitiation entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save RewardInitiation entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("RewardInitiation", id.toString(), this);
  }

  static load(id: string): RewardInitiation | null {
    return store.get("RewardInitiation", id) as RewardInitiation | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get user(): string {
    let value = this.get("user");
    return value.toString();
  }

  set user(value: string) {
    this.set("user", Value.fromString(value));
  }

  get pool(): string {
    let value = this.get("pool");
    return value.toString();
  }

  set pool(value: string) {
    this.set("pool", Value.fromString(value));
  }

  get tokens(): Array<string> | null {
    let value = this.get("tokens");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set tokens(value: Array<string> | null) {
    if (value === null) {
      this.unset("tokens");
    } else {
      this.set("tokens", Value.fromStringArray(value as Array<string>));
    }
  }

  get amounts(): Array<BigInt> | null {
    let value = this.get("amounts");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toBigIntArray();
    }
  }

  set amounts(value: Array<BigInt> | null) {
    if (value === null) {
      this.unset("amounts");
    } else {
      this.set("amounts", Value.fromBigIntArray(value as Array<BigInt>));
    }
  }

  get duration(): BigInt {
    let value = this.get("duration");
    return value.toBigInt();
  }

  set duration(value: BigInt) {
    this.set("duration", Value.fromBigInt(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }
}

export class Vest extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Vest entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Vest entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Vest", id.toString(), this);
  }

  static load(id: string): Vest | null {
    return store.get("Vest", id) as Vest | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get beneficiary(): string {
    let value = this.get("beneficiary");
    return value.toString();
  }

  set beneficiary(value: string) {
    this.set("beneficiary", Value.fromString(value));
  }

  get pool(): string {
    let value = this.get("pool");
    return value.toString();
  }

  set pool(value: string) {
    this.set("pool", Value.fromString(value));
  }

  get token(): string {
    let value = this.get("token");
    return value.toString();
  }

  set token(value: string) {
    this.set("token", Value.fromString(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }

  get value(): BigInt {
    let value = this.get("value");
    return value.toBigInt();
  }

  set value(value: BigInt) {
    this.set("value", Value.fromBigInt(value));
  }

  get period(): BigInt {
    let value = this.get("period");
    return value.toBigInt();
  }

  set period(value: BigInt) {
    this.set("period", Value.fromBigInt(value));
  }

  get txHash(): string {
    let value = this.get("txHash");
    return value.toString();
  }

  set txHash(value: string) {
    this.set("txHash", Value.fromString(value));
  }
}

export class Uniswap extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Uniswap entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Uniswap entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Uniswap", id.toString(), this);
  }

  static load(id: string): Uniswap | null {
    return store.get("Uniswap", id) as Uniswap | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get pool(): string | null {
    let value = this.get("pool");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toString();
    }
  }

  set pool(value: string | null) {
    if (value === null) {
      this.unset("pool");
    } else {
      this.set("pool", Value.fromString(value as string));
    }
  }
}

export class Collect extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Collect entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Collect entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Collect", id.toString(), this);
  }

  static load(id: string): Collect | null {
    return store.get("Collect", id) as Collect | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get token0Fee(): BigInt {
    let value = this.get("token0Fee");
    return value.toBigInt();
  }

  set token0Fee(value: BigInt) {
    this.set("token0Fee", Value.fromBigInt(value));
  }

  get token1Fee(): BigInt {
    let value = this.get("token1Fee");
    return value.toBigInt();
  }

  set token1Fee(value: BigInt) {
    this.set("token1Fee", Value.fromBigInt(value));
  }

  get pool(): string {
    let value = this.get("pool");
    return value.toString();
  }

  set pool(value: string) {
    this.set("pool", Value.fromString(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }
}

export class Reinvest extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save Reinvest entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save Reinvest entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("Reinvest", id.toString(), this);
  }

  static load(id: string): Reinvest | null {
    return store.get("Reinvest", id) as Reinvest | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get pool(): string {
    let value = this.get("pool");
    return value.toString();
  }

  set pool(value: string) {
    this.set("pool", Value.fromString(value));
  }

  get timestamp(): BigInt {
    let value = this.get("timestamp");
    return value.toBigInt();
  }

  set timestamp(value: BigInt) {
    this.set("timestamp", Value.fromBigInt(value));
  }
}

export class User extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  save(): void {
    let id = this.get("id");
    assert(id !== null, "Cannot save User entity without an ID");
    assert(
      id.kind == ValueKind.STRING,
      "Cannot save User entity with non-string ID. " +
        'Considering using .toHex() to convert the "id" to a string.'
    );
    store.set("User", id.toString(), this);
  }

  static load(id: string): User | null {
    return store.get("User", id) as User | null;
  }

  get id(): string {
    let value = this.get("id");
    return value.toString();
  }

  set id(value: string) {
    this.set("id", Value.fromString(value));
  }

  get managingPools(): Array<string> | null {
    let value = this.get("managingPools");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set managingPools(value: Array<string> | null) {
    if (value === null) {
      this.unset("managingPools");
    } else {
      this.set("managingPools", Value.fromStringArray(value as Array<string>));
    }
  }

  get ownedPools(): Array<string> | null {
    let value = this.get("ownedPools");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set ownedPools(value: Array<string> | null) {
    if (value === null) {
      this.unset("ownedPools");
    } else {
      this.set("ownedPools", Value.fromStringArray(value as Array<string>));
    }
  }

  get deposits(): Array<string> | null {
    let value = this.get("deposits");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set deposits(value: Array<string> | null) {
    if (value === null) {
      this.unset("deposits");
    } else {
      this.set("deposits", Value.fromStringArray(value as Array<string>));
    }
  }

  get withdrawals(): Array<string> | null {
    let value = this.get("withdrawals");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set withdrawals(value: Array<string> | null) {
    if (value === null) {
      this.unset("withdrawals");
    } else {
      this.set("withdrawals", Value.fromStringArray(value as Array<string>));
    }
  }

  get claimedRewards(): Array<string> | null {
    let value = this.get("claimedRewards");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set claimedRewards(value: Array<string> | null) {
    if (value === null) {
      this.unset("claimedRewards");
    } else {
      this.set("claimedRewards", Value.fromStringArray(value as Array<string>));
    }
  }

  get rewardInitiations(): Array<string> | null {
    let value = this.get("rewardInitiations");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set rewardInitiations(value: Array<string> | null) {
    if (value === null) {
      this.unset("rewardInitiations");
    } else {
      this.set(
        "rewardInitiations",
        Value.fromStringArray(value as Array<string>)
      );
    }
  }

  get vests(): Array<string> | null {
    let value = this.get("vests");
    if (value === null || value.kind == ValueKind.NULL) {
      return null;
    } else {
      return value.toStringArray();
    }
  }

  set vests(value: Array<string> | null) {
    if (value === null) {
      this.unset("vests");
    } else {
      this.set("vests", Value.fromStringArray(value as Array<string>));
    }
  }
}
